# Generated by Django 5.0.1 on 2025-03-08 19:05

import django.db.models.deletion
import django.utils.timezone
import propylon_document_manager.file_versions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="file",
            field=models.FileField(default="documents/default.pdf", upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file_owner",
            field=models.ForeignKey(
                default=propylon_document_manager.file_versions.models.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="fileversion",
            unique_together={("file_name", "file_owner", "version_number")},
        ),
    ]
