# Generated by Django 5.0.1 on 2025-03-08 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_fileversion_file_fileversion_file_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
