# Generated by Django 5.0.1 on 2025-03-08 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0003_alter_fileversion_uploaded_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
